[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\aim_arinc_429'

[projects.support]
path = 'Source\Custom Device Support\AIM ARINC 429 Support.lvproj'

[projects.cd]
path = 'Source\Custom Device\AIM ARINC 429 Custom Device.lvproj'

[projects.scripting_examples]
path = 'Source\Scripting Examples\Scripting Examples.lvproj'

[[build.steps]]
name = 'Scripting API'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Scripting API'

[[build.steps]]
name = 'System Explorer PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'System Explorer'

[[build.steps]]
name = 'Engine PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'My Computer'
build_spec = 'Engine'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Linux x64 Engine PPL'
type = 'lvBuildSpec'
project = '{support}'
target = 'Linux x64'
build_spec = 'Engine'

[[build.steps]]
name = 'Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'Linux x64'
build_spec = 'Engine Release'

[[package]]
type = 'nipkg'
control_file = 'control_custom_device'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\AIM' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\AIM'
'Source\\Built\\Errors' = 'ni-paths-NISHAREDDIR{nipaths_64_bitness_suffix}\LabVIEW Run-Time\{veristand_version}\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_scripting'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Scripting' = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\vi.lib\addons\VeriStand Custom Device Scripting APIs\AIM ARINC 429'
'Source\\Built\\Scripting Examples' = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\examples\NI VeriStand Custom Devices\AIM ARINC 429'
'Source\\Built\\Errors' = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\resource\errors\English'
